### ISSUE TITLE
Multichannel Pulses

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#107]
In reality, qubits are often controlled via multiple channels such that pulses must somehow be defined for more than a signel channel. Investigate options and prototypical solution.

**Comment by pbethke** [comment]
We also need to think about how to integrate markers into the sequencing. The Tektronix AWG we use has two marker channels per analog output, so for this device it would make sense to include them with the analog waveform. I am going to include this in the "multichannel hack" for now.

**Comment by lumip** [comment]
As far as I remember, markers can be seen as pulses that only take boolean values (0 or 1), is that correct? I'd suggest that, during definition, markers are simply added as an additional channel definition to the templates and the mapping to AWG marker channels is performed during the final hardware mapping stage, which maps logical channels in the defintions to the actual channels present on the hardware setup for a given experiment.

**Comment by lumip** [comment]
I thought a bit about how to implement multi-channel pulses and here are my thoughts:

### Goal ###
We want to model pulses that result in simultaneous output of waveforms on several channels. These waveforms are typically not unrelated but depend on each other to have meaningful semantics in manipulation qubit states.

### Approaches ###
#### I) Totally Independent PulseTemplates ####
In this approach, pulses for each channel are modelled independently of the other channels with separate PulseTemplate instances. Sequencing is invoked for separately for each. Only playback is synchronized.
**Pro**
- no changes to the code
- arbitrary composition of single-channel pulses to multi-channel
**Contra**
- semantical correspondences between pulses of different channels are not explicitely modelled
- inconsistencies between different channels are possible
-- different length of waveforms
-- different control flow (branching/looping). this could possibly be resolved using an additional compilation step that modifies the instruction sequences to account for that but that would be a very complicated and error prone implementation

#### II) PulseTemplates encode several channels ####
The atomic pulse templates (TablePulseTemplate and FunctionPulseTemplate) and Waveform objects define waveforms for an arbitrary number of pulses. The higher order templates allow only combination of subtemplates with identical numbers of channels, i.e., each modelled pulse is only valid for a certain channel number. Sequencing produces a single instruction sequence valid for all channels.
** Pro **
- same control flow for all channels, no inconsistencies
- correspondencies between channel pulses clearly modelled into one object
** Contra **
- no reuse of channel pulses
- cannot mix function and table atomics, i.e., at each point in time, all channel waveforms are either table- or function-defined

#### III) Class that combines atomic single-channel to multi-channel pulses ####
An additional class (e.g., MultiChannelPulseTemplate) combines an arbitrary number of single-channel atomic pulse templates to a multi-channel atomic pulse template. As above, higher order templates allow only combination of subtemplates with identical numbers and sequencing produces a single instruction sequence.
** Pro **
- same control flow for all channels
- reuse and arbitrary combintaiton of channel pulses (of equal length)
** Undecided (neither pro nor contra)**
- correspondencies between channel pulses modelled in a separate object

I think, a hybrid approach of II and III would serve us well, i.e., allowing to define multiple channels in the atomic templates but also introducing a MultiChannel class. I will evaluate this by trying.
