### ISSUE TITLE
Establish Coding Conventions

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#15]
To guarantee easy readability and maintainability of the code, conventions for syntax, documentation and testing must be established and followed by the developers.
Such conventions must first be established and documented in the wiki (https://github.com/qutech/qc-toolkit/wiki/Coding-Conventions).

**Comment by ekammerloher** [comment]
I would suggest to follow the [PEP 0008](https://www.python.org/dev/peps/pep-0008/) guidelines for code and [PEP 0257](https://www.python.org/dev/peps/pep-0257/) guidelines for docstrings.

**Comment by lumip** [comment]
Those guidelines are nice. @j340m3 and I have decided to stick to them.
I've referenced them in the aforementioned wiki page.
