### ISSUE TITLE
Version of python

### ISSUE THREAD

**Issue by ekammerloher** [qutech/qc-toolkit#16]
I think python 3.4 should be used to profit from an evolving language (things like [this](https://www.python.org/dev/peps/pep-0465/#why-should-matrix-multiplication-be-infix)). Developing with Python 2.7 is like developing on Windows XP.

### Sample of some packages
package | supports | comment
----------- | ------------- | -------------
NumPy/SciPy | python 3.2+ | since NumPy 1.5.0 / SciPy  0.9.0
matplotlib | python 3.1+ | since matplotlib 1.2
chaco | **python 2.7** | python 3 branch tests run 100%
PyVisa | python 3.2+ |
QuTiP | python 2.7+ | On website: "Version 3.3+ is highly recommended."
nose | python 3.1+ |
PyTables | python 3.1+  |
h5py | python 3.2+ |

**Comment by lumip** [comment]
@j340m3 and I discussed this a few hours ago and came to the same conclusion. Using Python 3.x is officially recommended by the language maintainers. The table suggests that most libraries are available for version 3.x (by now) so that we should not run into problems there...
