### ISSUE TITLE
Measurements to non atomic PT

### ISSUE THREAD

**Issue by qutech-lab** [qutech/qc-toolkit#167]
It would be good, to allow measurements within other templates than just atomic pulse templates.
Especially RepetitionPT.
(Frederik Wangelik)

**Comment by terrorfisch** [comment]
Currently measurements are bound to waveforms.

For now I will let the non-atomic pulse templates inject the measurements into the first waveform/EXEC instruction but there has to be a better way...

**Comment by terrorfisch** [comment]
Does not work as the RepetitionPT currently has no way to access the instructions generated by the body.

**Comment by terrorfisch** [comment]
Maybe a new MEAS instruction will seal the deal.

**Comment by terrorfisch** [comment]
This would also be a good oportunity to prepare the comeback of the CHAN instruction and non-atomic multi channel pulse templates.

**Comment by terrorfisch** [comment]
Implemented with merge #168 

I close this now. Please re-open if other PulseTempaltes are desired.

**Comment by terrorfisch** [comment]
Need measurements in ForLoopPT

**Comment by terrorfisch** [comment]
Implemented in #172
