### ISSUE TITLE
[[Not reproducible]] Program not updated on AWG when pulse parameters change

### ISSUE THREAD

**Issue by qutech-lab** [qutech/qc-toolkit#174]
Actual behaviour:
- Upload program with pulse parameter set 1
- Delete program with hardware setup remove_program
- Change pulse parameters to pulse parameter set 2
- Upload program again with same name and forcing the pulse update
- No errors are thrown, yet the original program using pulse parameter set 1 is executed

Fix:
- Reset AWG and upload again

(Pascal)

**Comment by terrorfisch** [comment]
This could be an error in the memory management. I will have to debug in the lab.

**Comment by qutech-lab** [comment]
This bug has only happened a few times and I do not know how to reproduce it at the moment

**Comment by qutech-lab** [comment]
Likely fixed now

-Simon
