### ISSUE TITLE
[[Not reproducible]] Uploading a program with a different name but same pulse does not return to idle pulse

### ISSUE THREAD

**Issue by qutech-lab** [qutech/qc-toolkit#175]
Behaviour:
- Upload program using pulse 1, parameter set 1 and name 1
- Program runs fine, once everytime tawg.channel_pair_AB.run_current_program is executed
- Upload program using pulse 1, parameter set 2 and name 2
- Program runs continously once tawg.channel_pair_AB.run_current_program, i.e. after one trigger it "runs forever" in a loop. It does not go back to the idle program on its own.
- No error messages are thrown

This obviously gives weird results in the data acquisition (I don't know how the data acquisition is triggered in this scenario).

Fix:
- Reset AWG
- Upload program using pulse 1, parameter set 2 and name 2
- Program runs fine

**Comment by terrorfisch** [comment]
Which program runs continously? ```name 1``` or ```name 2```?

**Comment by terrorfisch** [comment]
This could be an error in the memory management. I will have to debug in the lab. Possibly the same bug as #174

**Comment by qutech-lab** [comment]
This bug has only happened a few times and I do not know how to reproduce it at the moment

**Comment by qutech-lab** [comment]
Likely fixed now

-Simon
