### ISSUE TITLE
Do not reconfigure Alazar if program without measurements armed

### ISSUE THREAD

**Issue by qutech-lab** [qutech/qc-toolkit#179]
Scenario:
Arm and run program 1 with measurements defined
Arm and run program 2 with no measurements
Run program 1 again

Desired behaviour:
No time should be lost by needlessly reconfiguring the data acquisition. Just retain the configuration for program 1. Program 2 should be written in such a way that it does not trigger the data acquisition by the user.

-Pascal

**Comment by terrorfisch** [comment]
@pcerf This should be already the case as only those dacs are armed, that are associated with the program. Did you experience something different?

**Comment by qutech-lab** [comment]
This might have been a misunderstanding, I will report back once I have tested this.
