### ISSUE TITLE
Allow mapping of non-scalar parameters

### ISSUE THREAD

**Issue by qutech-lab** [qutech/qc-toolkit#216]
I.e. if a pulse uses the non-scalar parameter M[0] and M[1], it might be nice to map those two elements differently using a mapping pulse template (for example M[0] -> M[0]+a, M[1] -> M[1] + b).

-Pascal

**Comment by terrorfisch** [comment]
This is already possible:
```python
import sympy
from sympy.abc import a, b, M
parameter_mapping = {'M': M + sympy.Array([a, b])}
```
or
```python
parameter_mapping = {'M': ['a + M[0]', 'b + M[1]']}
```

I will create an issue to document this.
