### ISSUE TITLE
ForLoopPT should raise a warning if there is a constraint for the loop index

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#232]
It is currently possible to create a ForLoopPulseTemplate with parameter constraints affecting the loop index variable. However, the validation of the constraints is performed before the loop unrolling in the build_sequence() method, such that a ParameterNotProvidedException is thrown in this case.
We should either
1) allow constraints affecting the loop index variable and fix build_sequence()
2) forbid such constraints and throw and exception during object initialization if one is present

**Comment by terrorfisch** [comment]
I think the place for such a constraint would be the body template or the user formulates it in terms of the loop range.

I would not raise an exception but maybe a warning if there is a constraint for the loop index.
