### ISSUE TITLE
Specify RepetitionPulseTemplate documentation

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#234]
RepetitionPulseTemplate is advertised as "The equivalent to a simple for-loop in common programming languages in qctoolkit's pulse modelling.". With ForLoopPT we have another template with that role which is also more expressive. Is there any reason we still hang on to RepetitionPT?

Suggestion: RepetitionPulseTemplate should be deprecated and removed in the future.

**Comment by terrorfisch** [comment]
RepetitionPT does repeat the same pulse while the ForLoopPT changes the body. Therefore, it has a significantly better performance during sequencing.

The doc string for the RepetitionPT is misleading.
