### ISSUE TITLE
Clear all command for programs

### ISSUE THREAD

**Issue by qutech-lab** [qutech/qc-toolkit#247]
It would be nice to have a clear all command which quickly clears all registered programs from all awgs and daqs. The current command remove_program is very slow if applied to all programs since it also tries to clear the AWG memory by removing all waveforms (which is slow and not needed if one wants to clear everything).

For now I have a workaround but this would be nice to have.

- Pascal

**Comment by terrorfisch** [comment]
Implemented in #267
