### ISSUE TITLE
RepetitionPulseTemplate sequences body if repetition count is null

### ISSUE THREAD

**Issue by terrorfisch** [qutech/qc-toolkit#248]
The adding of the repetition instruction and sequencing of the body should only happen if the repetition count is larger null

**Comment by superpostition** [comment]
not-working-example:`from qctoolkit.pulses import TablePT
from qctoolkit.pulses import RepetitionPT
from qctoolkit.pulses.plotting import plot

entry_list = [(0, 0),
              (2, 2, 'hold'),
              (4, 3, 'linear'),
              (6, 0, 'jump')]
              

entries = {0: entry_list}

template = TablePT(entries)

template = RepetitionPT(template, 'n_rep')

_ = plot(template, {'n_rep':0}, sample_rate=100, show=True)`

**Comment by terrorfisch** [comment]
For me this crashes [in the plotting routine](https://github.com/qutech/qc-toolkit/blob/93ec4abd3986594764724426d187debe805fe338/qctoolkit/pulses/plotting.py#L219) because there are no points to plot. Which is a seperate bug by the way.
