### ISSUE TITLE
Serializer deserializes the same pulse twice

### ISSUE THREAD

**Issue by superpostition** [qutech/qc-toolkit#250]
pulses.SequencePT() raises

Exception: Identifier '<...>' assigned twice.

if subplustemplates consist of same subpulstemplates.

**Comment by terrorfisch** [comment]
The problem occurs because the serializer deserializes the same pulse/file twice. This means there are two distinct objects with the same identifier which leads to an error when one wants to save them again.

**Comment by terrorfisch** [comment]
Changed priority as this is partially fixed now.
