### ISSUE TITLE
Global pulse registry/registration not correctly implemented; if fixed, problems with tests

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#276]
The current implementation of the global pulse/serializable registration is flawed. The second if statement in the relevant excerpt from `Serializable.__init__()` below does not evaluate to True if the standard default_pulse_registration - a WeakValueDictionary() - is employed (see at the end), hence pulses are never registered.

        if registration is None:
            registration = default_pulse_registration

        if identifier and registration:
            if identifier in registration:
                raise RuntimeError('Pulse with name already exists', identifier)
            else:
                registration[identifier] = self

Changing that line into `if identifier and registration is not None:` will result in registered pulses... and a majority of tests failing, since pulse identifier are assigned multiple times.
We would need to fix all tests or find a better solution to avoiding duplicate identifiers than a global registry.

------
apparently instances of WeakValueDictionary cannot be checked for presence using `if <instance>:` (as seen in tests)

**Comment by terrorfisch** [comment]
Rename registration to the correct registry
