### ISSUE TITLE
Basic Hardware Driver Test

### ISSUE THREAD

**Issue by terrorfisch** [qutech/qc-toolkit#3]
Implement a test in MATLAB which

- generates a pulse
- uploads it to arbitrary AWG
- starts playback and simultaneously records with a Data Acquisition Card
- compares recorded data and generated data

**Comment by hbluhm** [comment]
Preferably the acquisition device should be a (moslty) generic (buffered) SM channel so that oscilloscopes can also be used. 

To test higher level functions of the interface to AWGs, a virtual AWG/scope that closes the loop without going through hardware could quite be useful.

**Comment by terrorfisch** [comment]
The current test does not rely on smrun, since we wanted it to have minimal dependencies and just test the drivers.

**Comment by hbluhm** [comment]
Makes sense, though you can still use the generic driver functions.

Hendrik

**Comment by lumip** [comment]
I think this is no longer relevant and does not refer to this project anyway.
If still relevant, the issue should be re-opened in the pulsecontrol repository.
