### ISSUE TITLE
Tests for SequencePulseTemplate

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#32]

**Comment by j340m3** [comment]
SequencePulseTemplate:

* Since the Sequencer will compute the measurement windows, do we still need "get_measurement_windows" in here? 
* "requires_stop" is still buggy:
    * The passed Dict "parameters" is never used. We check all parameters, even when not asked.
    * I think we need a for loop over all the subtemplates rather than only check the first one
    * In the last line, we call requires_stop on a string.

If these issues are cleared, the last test can be implemented.
