### ISSUE TITLE
Serializing/Storing of Pulse Templates

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#34]
As a user of PulseTemplates, I wish to be able to save and load PulseTemplate to/from a persistent storage to simplify reuse. PulseTemplates should be stored in a readable way to allow modification of stored PulseTemplates without invoking the software. It should be possible to either store an entire PulseTemplate hierarchy in a single file or split the hierarchy, store different subtrees in separate files that reference each other.

During the 3rd meeting it was decided to use JSON-files as the primary format of storing PulseTemplates (see #8 for a discussion on different storage mechanisms).

To allow for flexibilty, PulseTemplates should not know how they are stored. This should be encapsualted in a *PulseTemplateSerializer* object which provides an interface for PulseTemplates to serialize and deserialize their internal information from an abitrary persistent storage.
PulseTemplates need to be identified by a unique name to derive file names and construct meaningful references. However, it may be possible to embed PulseTemplates only relevant for a single hierarchy into the serialization of their parent PulseTemplate. In this case, no identifier is needed.

Proposed changes to the current design:

Introduce new abstract class *PulseTemplateSerializer*:
- *deserialize(storage_path: str): PulseTemplate*
- methods allowing PulseTemplate instances to store internal information

PulseTemplate:
- add method *serialize(serializer: PulseTemplateSerializer)* - an additional argument carrying some serialization context may be required
- add optional member *name: str*. If *name* is set, calls to *serialize* will result in information being written to a separate file with a corresponding name. Otherwise, information of the PulseTemplate will be embedded in its parent's file.

**Comment by lumip** [comment]
Changes to the intended design:
Introduce new base class *Serializable*:
- method *get_serialization_data(serializer: Serializer) -> Dict[str, Any]* - return a dictionary of elementary (/built-in) types that can be easily converted by Python's JSON encoder
- property *identifier -> Optional[str]* - return a unique, human-readable identifier, indicating that the Serializable object shall be stored separately.
PulseTemplates and ParameterDeclarations will be Serializable.

Introduce new class *Serializer*:
- method *serialize(serializable: Serializable) -> str* - return a JSON representation of the Serializable object. If it has an identifier, its JSON representation is stored internally and just the identifier is returned.

**Comment by pbethke** [comment]
I like it. Related to this issue is the question of serializing mapping functions. 
The problem there is that functions cannot be pickled. There are several approaches for this. I am going to open a separate issue for that.
