### ISSUE TITLE
Configure Travis

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#36]
[Travis CI](https://travis-ci.org/) is a continuous integration tool for github projects, performing tests on each push to ensure that code is working as intended. It should be used by our project and must configured accordingly.
If possible, maybe we should separate tests of the actual code and "meta"-tests for missing documentation.

**Comment by lumip** [comment]
@ekammerloher : Neither @j340m3 nor I can add the qc-toolkit repository to Travis. I think the problem is that we are not owners of the repository (or lack some other required rights). Can you do this?

**Comment by ekammerloher** [comment]
I added @j340m3 as an administrator and activated Travis CI for qc-toolkit.

The configuration of .travis.yml is not good yet and the tests need to return the correct exit code for success or failure. Maybe something like this:

```
--- a/tests/run_tests.py
+++ b/tests/run_tests.py
@@ -6,4 +6,5 @@ import unittest
 #sys.path.insert(0, basePath)

 suite = unittest.TestLoader().discover('.', pattern='*Test*.py')
-unittest.TextTestRunner(verbosity=2).run(suite)
+ret = not unittest.TextTestRunner(verbosity=2).run(suite).wasSuccessful()
+sys.exit(ret)
```

**Comment by lumip** [comment]
See #38
