### ISSUE TITLE
Pulse For-Loops/Repetitions

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#42]
As a user of the pulse library, I would like to be able to specify that (parts of) a pulse should be repeated a fixed number of times without interrupting execution or depending on hardware triggers.

While the desired behavior could be achieved using LoopPulseTemplate with a specifically tailored Condition subclass, maybe a more direct mechanism to express such fixed amounts of iterations would be beneficial.
Possibilities are:
- LoopPulseTemplate and a ForLoopCondition subclass
- A specific RepetitionPulseTemplate class that holds a reference to a subtemplate which is repeated a given number of times
- Extend SequencePulseTable to allow how often each subtemplate should be repeated before moving on to the next (this would be similar to how the same mechanism works in pulse groups (?) in pulsecontrol).

@qutech/owners @qutech/bluhm-group Do you have preferences?

**Comment by hbluhm** [comment]
It seems to me that extending SequencePulseTable would induce the least code overhead when defining loops without being awkward. One of the other options may also become relevant in the future and could be kept in the list of desirable features. Here I would lean towards a ForLoopCondition subclass as it probably recycles better.
