### ISSUE TITLE
Pulse Parameter Dependencies

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#44]
As a user of the pulse library, I want to be able to formulate dependencies/constraints between parameters in a pulse template definition.

@qutech/owners @qutech/bluhm-group This was mentioned briefly during the last meeting and I didn't catch it all I think. Can you elaborate what exactly is required and maybe provide an example?

**Comment by hbluhm** [comment]
A simple and common example would be a two-channel pulse (i.e. with two signal voltages V1 and V2) which moves along V1=-V2. For each stage of the pulse, only one amplitude parameter would be needed for the two channels. Another example would be that some time is added to one stage of the pulse and subtracted from another.
In pulsecontrol, this is implemented via pardefs that map input parameters onto the various pulse description parameters. The map can be a matrix for linear transformation or an arbitrary function, I think.

**Comment by lumip** [comment]
Implemented via parameter constraints
