### ISSUE TITLE
TablePulseTemplate is horribly bugged

### ISSUE THREAD

**Issue by pbethke** [qutech/qc-toolkit#47]
I played around with TablePulseTemplate a bit, trying to build a square pulse. There were a lot of calls to non-existent list methods, etc. I fixed a few of those and pushed my fixed version to a new branch (issue-47). I have found a lot of ambigous points and would ask either @lumip or @j340m3 to have a look anywhere i have put a TODO comment.

**Comment by lumip** [comment]
I'll look into this. The TablePulseTemplate was not tested as of yet because I wanted to make some changes to the definition of parameters in the time space (issue #31 ) before I implement the tests. It's the next thing I will work on.

**Comment by lumip** [comment]
Since the changes made in the branch are now included in the branch issue-31 and other bugs will (hopefully) be found during testing (issue #30), this issue is somewhat a duplicate and I closed it.
