### ISSUE TITLE
Include python 3.4 in the travis tests

### ISSUE THREAD

**Issue by pbethke** [qutech/qc-toolkit#48]
The typing module from 3.5 is available as a backport to 3.4 on pypi. Do we rely on any other 3.5 features? Why not just include py3.4 in the travis tests and maybe accidentally support the current stable version (especially since it takes the scientific distributions a while to switch once 3.5 is released)? @ekammerloher?

**Comment by lumip** [comment]
Including python 3.4 in the tests (and ensuring backwards compatability if necessary) won't do any harm and should not result in too much additional work, so I think we can do this without further discussion.

**Comment by pbethke** [comment]
I have a patch for the setup.py which checks the python version and requires the typing backport for 3.4 from pypi. I'll send a pull request as soon as I have tested it

**Comment by lumip** [comment]
Done.
