### ISSUE TITLE
Change Mapping Class to Implement a Mapping to a Single Parameter

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#58]
The module file *pulses/SequencePulseTemplate* defines a *Mapping* class that is used in the *SequencePulseTemplate* class to map parameters given to that class to its sub-PulseTemplates. This can mean changing the name and giving a function that mathematically transforms parameter values. This is exactly what we need also for issue #44 . However, the *Mapping* class represent a mapping from an incoming parameter set to an outgoing parameter set. For issue #44, a mapping from parameter set to a single parameter is needed.
What is to be done?:
- Implement a class which maps values from multiple parameters to a single new one. This class could then be treated as a parameter itself (e.g. a *Derived-* or *MappedParameter*). Do this by extracting corresponding already existing code from *Mapping*.
- To avoid code duplication, adapt *Mapping* to use the newly introduced class while maintaining its current functionality.

**Comment by pbethke** [comment]
I have a simple example for how a user might want to use the software. A lot of the functionality is not implemented yet.

[Example](https://gist.github.com/pbethke/6dc0076e33daf5be867d)

**Comment by hbluhm** [comment]
It seems to me that using only one class mapping a set of input to a set of output parameters without constraints on relative sizes would be sufficient for the start. "Slim" versions for special cases can be added later if that substantially improves usability. The example I saw looking over Patrick's shoulder looked good.
