### ISSUE TITLE
Sequencer Should Compute Measurement Windows

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#66]
Currently, measurement windows are provided by the method get_measurement_windows of the PulseTemplate class family. This is somewhat inconsistent to the way pulses are instantiated and leads to code duplication, since this method has to perform much of the tasks Sequencer is designed to do. Thus, Sequencer should compute measurement windows and the method get_measurement_windows should be removed.

Steps:
- Change interface of Sequencer or SequencingElement such that measurement windows can be communicated between both
- Extend Sequencer to accumulate measurement windows
- Remove get_measurement_windows method from PulseTemplate and subclasses

**Comment by j340m3** [comment]
Current status: I coupled measurements to `TablePulseTemplates` and `FunctionPulseTemplates`, in which one can define the measurement windows concerning this leaf node. 
In this way, the sequencer may stay unchanged, the waveforms stay untouched so does the according measurement. Only when the `sample`-function of a waveform is called, the `measurement_windows`  should also be called, to get the according measurement windows.

**Comment by lumip** [comment]
All changes currently reside in a separate branch. Should be checked and merged or edited if necessary.

**Comment by terrorfisch** [comment]
As stated in #132 in measurement windows need identifiers which may differ for the same waveform. Therefore the sequencer should collect them seperatly. I'm thinking about storing them in the corresponding instruction block or returning them together with the ImmutableInstructionBlock from `Sequencer.build()`

**Comment by terrorfisch** [comment]
The measurement windows are stored in the waveforms for now
