### ISSUE TITLE
Convenience Functions for SequencePulseTemplate

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#74]
Currently, SequencePulseTemplate can only be constructed using its constructor (duh!). Allowing to add more subtemplates and external parameters after object constructions as done in TablePulseTemplate is more convenient to users.

**Comment by lumip** [comment]
Patrick stated, that this would not be required and thus no effort should be made towards the realization of this issue.

**Comment by lumip** [comment]
Having used the SequencePulseTemplate a bit in examples, I'd find it much easier if I could add to them using an add method as for the TablePulseTemplate.
Additionally, the following two features would be very convenient:
- Use identity mapping for parameters as default, if no explicit mapping is provided
- Derive external parameters from left-hand sides of the mappings

**Comment by pbethke** [comment]
I still dislike the addition of an add method. The verification leeds to a lot of spaghetti code like in ```TablePulseTemplate.add_entry``` and requires an enormous amount of unit tests.

* Identity mapping as a default is a nice idea in principle. There is an ABS in the collections module that helps with the construction of the dict-interface. I'll have a look if an identity mapping is reasonably easy to implement, but I am optimistic.

* This is also possible. However, at the moment we use the external parameters explicitly provided by the user to verify that the mappings are complete and minimal. These checks are going to be impossible to make if we derive them from the mappings instead. I don't have an intuition on which way is better at the moment.

**Comment by pbethke** [comment]
There is now a working implementation of an identify mapping class now in the ```identity_mapping``` branch. While writing tests for it, I noticed that implicit mappings are indeed not very useful without implicit external parameters.

**Comment by lumip** [comment]
- I'd include default identity mapping as a default as long as no explicit mapping is given. If there are name collisions, which we can easily detect, we could either:
-- throw an exception
-- extend the name of the parameter by some identifier of the subtemplate, e.g., 'down' -> 'sub1.down'
-- do nothing. In some case, we may even want to map to parameters with the same name from different subtemplates to the same value incoming parameter.
I think as a default behavior, doing nothing is reasonable (it is what I would expect). If the user wants something specific to happen, he should provide an explicit mapping.

- If parameter names of the SequencePulseTemplate were derived from the given mappings, they would be complete and minimal by definition, wouldn't they? In this case, we wouldn't need the checks.

**Comment by hbluhm** [comment]
I wonder if add methods could be combined with a slimmer syntax like overloading '*'. It is not obvious how to handle parameters that way. They would either have to be defined by lower levels or later passed from a higher level. The motivation is to be able to write algorithms as clearly as possible.

**Comment by terrorfisch** [comment]
I removed the parameter duplication check for the `@` operator in #170 and consider this issue resolved.
