### ISSUE TITLE
Implement rest of FunctionPulseTemplate

### ISSUE THREAD

**Issue by pbethke** [qutech/qc-toolkit#83]
FunctionPulseTemplate is an important low-level pulse type that allows users to create smooth pulse shapes like gaussians, etc. The implementation however, is still lacking an implementation for the ```build_sequence``` method. This is non-trivial and should be done by someone with an understanding of how registering waveforms in the sequencer works at the moment. Related to #66.

**Comment by j340m3** [comment]
Implemented similar to the ```TablePulseTemplate.build_sequence``` with a little help by @terrorfisch.

**Comment by lumip** [comment]
Have you pushed/merged?

**Comment by j340m3** [comment]
Yes but I pushed into the wrong branch. Now its merged.
